Cargo.toml: use ffmpeg-next 8.1.0
Fix macos-14 builds breaking due to errors like:

|error[E0004]: non-exhaustive patterns: `sys::AVCodecID::AV_CODEC_ID_JPEGXS`, `sys::AVCodecID::AV_CODEC_ID_ADPCM_IMA_HVQM4`, `sys::AVCodecID::AV_CODEC_ID_ADPCM_IMA_PDA` and 7 more not covered

Signed-off-by: Trevor Gamblin <tgamblin@baylibre.com>