aarch64 support and workflow cleanups (#125)
* Cargo.toml: sort dependencies alphabetically

Signed-off-by: Trevor Gamblin <tgamblin@baylibre.com>

* build.yml: simplify before-script-linux

We don't need the pre_build scripts after this.

Signed-off-by: Trevor Gamblin <tgamblin@baylibre.com>

* build.yml: switch to manylinux 2_34

This is based on a newer OS, which should involve less effort to jump to
newer versions from later.

Signed-off-by: Trevor Gamblin <tgamblin@baylibre.com>

* build.yml: set FFMPEG_VERS to 8.0.1-5

The upstream naming convention changed to use hyphens instead of a mix
of hyphens and underscores, so fix that in DOWNLOAD_URL.

Signed-off-by: Trevor Gamblin <tgamblin@baylibre.com>

* Cargo.toml: use ffmpeg-next 8.1.0

Fix macos-14 builds breaking due to errors like:

|error[E0004]: non-exhaustive patterns: `sys::AVCodecID::AV_CODEC_ID_JPEGXS`, `sys::AVCodecID::AV_CODEC_ID_ADPCM_IMA_HVQM4`, `sys::AVCodecID::AV_CODEC_ID_ADPCM_IMA_PDA` and 7 more not covered

Signed-off-by: Trevor Gamblin <tgamblin@baylibre.com>

* build.yml: use ubuntu-24.04 runner

Signed-off-by: Trevor Gamblin <tgamblin@baylibre.com>

* build.yml: enable aarch64 on ubuntu-24.04-arm runner

Use an arm runner for aarch64. FFMPEG_DIR also needs to be set as a
docker option so that it persists beyond the before-script-linux section
and we pick up the pyav-ffmpeg content correctly.

We no longer need .cargo/config.toml with this change, since the options
in there were for cross-compile.

Signed-off-by: Trevor Gamblin <tgamblin@baylibre.com>

---------

Signed-off-by: Trevor Gamblin <tgamblin@baylibre.com>